### ISSUE TITLE
Content migration

### ISSUE THREAD

**Issue by robdirienzo** [templesmc/study-away#1]
Starting to pull content over and replicate page structure from existing site.

**Comment by robdirienzo** [comment]
@cmchale - I saw you created a couple more pages, where did you leave off?

**Comment by astratagem** [comment]
I should probably unfollow this repo :)

**Comment by loafintree** [comment]
Meh. Not a big deal. Not really doing anything on it.

On Monday, February 29, 2016, Chris Montgomery notifications@github.com
wrote:

> I should probably unfollow this repo :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/templesmc/study-away/issues/1#issuecomment-190416643.

## 

---

Todd M. Broadbent
_President_
_Loafin' Tree LLC_
_Phone:_ 267.608.9217
www.loafintree.com
LinkedIn Profile http://www.linkedin.com/pub/todd-broadbent/12/66b/372
_Google Chat:_ loafintree@gmail.com
_Skype:_ loafintree

_CONFIDENTIALITY NOTICE:_  The content of this email and any attachments
are for the exclusive and confidential use of the intended recipient. If
you are not the intended recipient, please do not read, distribute or take
action in regards to this message. If you have received this in error,
please notify us immediately by return email and promptly delete this
message and its attachments from your computer system.
